# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "SGE Monitor"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "__base.tt"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag:   '%>'
      PRE_PROCESS: 'layouts/__macro.tt'

plugins:
  'Cache::CHI':
    driver: Memory
    global: 1
    honor_no_cache: 1
